### ISSUE TITLE
can't run on ios,

### ISSUE THREAD

**Issue by camellieeee** [Ice-MT/react-native-imUI#1]
<img width="597" alt="2016-09-27 11 14 41" src="https://cloud.githubusercontent.com/assets/18331008/18859109/c9c58850-84a3-11e6-9219-578b5aae6508.png">
How to solve this error?

**Comment by Ice-MT** [comment]
![58ee246f-7835-40ea-9636-480bb58bddd3](https://cloud.githubusercontent.com/assets/9745974/18860559/0613f7c6-84b1-11e6-8f1a-50b33ce271e2.png)
open reacrNativeImUI.xcworkspace
not reacrNativeImUI.xcodeproj
